"""empty message

Revision ID: 57538577a9e4
Revises: 6e26bd0bb665
Create Date: 2026-01-31 13:52:39.298866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57538577a9e4'
down_revision = '6e26bd0bb665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout', schema=None) as batch_op:
        batch_op.drop_column('sold_count')
        batch_op.drop_column('quantity')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sold_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('sold_count')
        batch_op.drop_column('quantity')

    with op.batch_alter_table('checkout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sold_count', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
